name: sberbank_acquiring
description: Flutter Sberbank Acquiring SDK is a simple way to integrate payments into your mobile application.
version: 2.0.0
repository: https://github.com/MadBrains/Sberbank-Acquiring-SDK-Flutter
issue_tracker: https://github.com/MadBrains/Sberbank-Acquiring-SDK-Flutter/issues
homepage: https://madbrains.ru/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  comparer: ^2.0.1
  # meta: ^1.3.0
  http: ^0.13.3
  webview_flutter: ^2.0.4
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  json_serializable: ^4.1.1